### PR TITLE
Improve code coverage on class ByCssSelectorOrByNameOrById

### PR DESCRIPTION
**Pull request by andrelugomes**
Hi guys,

Increase ByCssSelectorOrByNameOrById.class code coverage on 97%.

I added Mockito inside pom.xml.

I will work more about code coverade, ok?

### CODE REVIEW

**Comment by dgageot** [comment]
@andrelugomes Thank you for the work, I commented on things that an be improved. Feel free to add some more coverage!

**Comment by andrelugomes** [comment]
Hi,

I will change and folow your tips. :+1:

**Comment by andrelugomes** [comment]
@dgageot, all done!

**Comment by dgageot** [comment]
@andrelugomes Thank you!

**Comment by dgageot** [comment]
@andrelugomes FYI, I've simplified the tests even more in this commit 6270bac5833ec6c1299f5b8bb837f5fe741681d4
It makes the tests look more like the rest of the codebase

**Comment by andrelugomes** [comment]
@dgageot ... nice :)

**Pull request merged**
